version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbit-service
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  history-ms:
    image: univandockerimages.azurecr.io/univan/history:1.1
    container_name: historyService
    environment:
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbit-service:5672
      - ConnectionStrings__HistoryDatabase=Server=tcp:tccunivanfinal.database.windows.net,1433;Initial Catalog=history;Persist Security Info=False;User ID=tccunivan;Password=Project!123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    ports: 
      - "5003:80"
    depends_on:
      - rabbitmq

  notification-ms:
    image: univandockerimages.azurecr.io/univan/notification:1.1
    container_name: notificationService
    environment:
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbit-service:5672
      - ConnectionStrings__NotificationDatabase=Server=tcp:tccunivanfinal.database.windows.net,1433;Initial Catalog=notification;Persist Security Info=False;User ID=tccunivan;Password=Project!123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
      - EmailSettings__ApiKey=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
    ports: 
      - "5002:80"
    depends_on:
      - rabbitmq

  univan-ms:
    image: univandockerimages.azurecr.io/univan/univan:1.2
    container_name: univanService
    environment:
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbit-service:5672
      - ConnectionStrings__UnivanDatabase=Server=tcp:tccunivanfinal.database.windows.net,1433;Initial Catalog=univan;Persist Security Info=False;User ID=tccunivan;Password=Project!123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
      - BlobSettings__ConnectionString=DefaultEndpointsProtocol=https;AccountName=tccunivan;AccountKey=qMdUYW616zG+e1AWdCUEmpJK48sPfz6xpb+UJ9EnHyMVHIoYEEbdxzFchBWi9Z3QNR/de6+ZQua1+AStKW9u0g==;EndpointSuffix=core.windows.net
    ports: 
      - "5000:80"
    depends_on:
      - rabbitmq

  carpool-ms:
    image: univandockerimages.azurecr.io/univan/carpool:1.4
    container_name: carpool
    environment:
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbit-service:5672
      - ConnectionStrings__CarpoolDatabase=Server=tcp:tccunivanfinal.database.windows.net,1433;Initial Catalog=carpool-service;Persist Security Info=False;User ID=tccunivan;Password=Project!123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
      - ConnectionStrings__Redis=tccunivan.redis.cache.windows.net:6380,password=jEBBOe6xnJItJPdBkjnb83yPLo3o7Mwu4AzCaLhjf68=,ssl=True,abortConnect=False
      - UnivanService__Url=http://univanService/api/
    ports: 
      - "5001:80"
    depends_on:
      - rabbitmq

  routes-ms:
    image: univandockerimages.azurecr.io/univan/routes:latest
    container_name: routes
    environment:
      - SERVER_PORT=80
      - MAPS_KEY=AIzaSyBxE3WWoAjcEUk4ttI1La96XO_JeWzXdM4
      - LISTENER_QUEUE=routes.listener.queue
      - DATABASE_URL=jdbc:sqlserver://tccunivanfinal.database.windows.net:1433;database=routes;user=tccunivan@tccunivanfinal;password=Project!123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - DATABASE_DIALECT=org.hibernate.dialect.SQLServerDialect
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - DDL_AUTO=create
      - RABBIT_HOST=rabbit-service
    ports:
      - "5004:80"
    depends_on:
      - rabbitmq

  api-gateway:
    image: univandockerimages.azurecr.io/univan/gateway:latest
    container_name: gateway
    environment:
      - SERVER_PORT=80
      - JWT_SECRET=jwtsecretunivantokenkeygenerator
      - FRONTEND_URL=http://localhost:4200
      - UNIVAN_URL=http://univanService:80
      - CARPOOL_URL=http://carpool:80
      - HISTORY_URL=http://historyService:80
      - ROUTES_URL=http://routes:80
    ports:
      - "8080:80"

networks:
  default:
    driver: bridge